-- local cmp = require 'cmp'
-- local lspkind = require 'lspkind'
--
-- cmp.setup({
-- 	snippet = {
-- 		expand = function(args)
-- 			require 'luasnip'.lsp_expand(args.body)
-- 		end
-- 	},
-- 	formatting = {
-- 		fields = { "kind", "abbr", "menu" },
-- 		format = function(entry, vim_item)
-- 			local kind = require("lspkind").cmp_format({ mode = "symbol_text", maxwidth = 50 })(entry, vim_item)
-- 			local strings = vim.split(kind.kind, "%s", { trimempty = true })
-- 			kind.kind = " " .. (strings[1] or "") .. " "
-- 			kind.menu = "    [" .. (strings[2] or "") .. "]"
--
-- 			return kind
-- 		end,
-- 	},
-- 	mapping = cmp.mapping.preset.insert({
-- 		['<C-b>'] = cmp.mapping.scroll_docs(-4),
-- 		['<C-f>'] = cmp.mapping.scroll_docs(4),
-- 		['<C-Space>'] = cmp.mapping.complete(),
-- 		['<C-e>'] = cmp.mapping.abort(),
-- 		['<CR>'] = cmp.mapping.confirm({ select = true }),
-- 	}),
-- 	sources = cmp.config.sources({
-- 		{ name = 'nvim_lsp' },
-- 		{ name = 'path' },
-- 		{ name = 'nvim_lsp_signature_help' },
-- 	}, {
-- 		{ name = 'buffer' },
-- 		{ name = 'luasnip' },
-- 		{ name = 'css-variables' },
-- 		{ name = 'cmp-tw2css' },
-- 	})
-- })
--
-- -- Set configuration for specific filetype.
-- cmp.setup.filetype('gitcommit', {
-- 	sources = cmp.config.sources({
-- 		{ name = 'git' }, -- You can specify the `git` source if [you were installed it](https://github.com/petertriho/cmp-git).
-- 	}, {
-- 		{ name = 'buffer' },
-- 	})
-- })
--
-- -- Use buffer source for `/` and `?` (if you enabled `native_menu`, this won't work anymore).
-- cmp.setup.cmdline({ '/', '?' }, {
-- 	mapping = cmp.mapping.preset.cmdline(),
-- 	sources = cmp.config.sources({
-- 		{ name = 'nvim_lsp_document_symbol' }
-- 	}, {
-- 		{ name = 'cmdline_history' },
-- 		{ name = 'buffer' }
-- 	})
-- })
--
-- -- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
-- cmp.setup.cmdline(':', {
-- 	mapping = cmp.mapping.preset.cmdline(),
-- 	matching = { disallow_symbol_nonprefix_matching = false },
-- 	sources = cmp.config.sources({
-- 		{ name = 'path' },
-- 	}, {
-- 		{ name = 'cmdline_history' },
-- 		{ name = 'cmdline' }
-- 	})
-- })
--
--
-- local sign = function(opts)
-- 	vim.fn.sign_define(opts.name, {
-- 		texthl = opts.name,
-- 		text = opts.text,
-- 		numhl = ''
-- 	})
-- end
--
-- sign({ name = 'DiagnosticSignError', text = '✘' })
-- sign({ name = 'DiagnosticSignWarn', text = '▲' })
-- sign({ name = 'DiagnosticSignHint', text = '⚑' })
-- sign({ name = 'DiagnosticSignInfo', text = '' })
