-- -- =============================================================================
-- -- Neovim LSP Configuration - Modern vim.lsp.config (Neovim 0.11+)
-- -- =============================================================================
-- --
-- -- This configuration uses the modern vim.lsp.config API for automatic LSP startup.
-- -- Servers start automatically when opening supported filetypes.
-- --
-- -- Servers:
-- --   • typescript-tools.nvim: TypeScript/JavaScript with enhanced features
-- --   • Biome: Linting and formatting for JS/TS/JSON files
-- --
-- -- Features:
-- --   ✅ Automatic LSP startup based on filetypes
-- --   ✅ typescript-tools.nvim with enhanced TypeScript support
-- --   ✅ Biome for linting and formatting
-- --   ✅ Performance optimized settings
-- --   ✅ Format-on-save integration
-- --   ✅ Diagnostic handling
-- --   ✅ Performance mode for large projects (toggle via performance_mode variable)
-- --
-- -- Configuration:
-- --   • typescript-tools.nvim: Configured in lua/plugins.lua
-- --   • performance_mode: true = maximum speed (disables autoimports, reduces memory)
-- --                       false = full features (default)
-- --
-- -- =============================================================================
--
-- if vim.g.vscode then
-- 	return
-- end
--
-- local _ = require('lib.fp')
-- local lib = require('lib')
--
-- local format_on_save = require('format-on-save')
-- local formatters = require('format-on-save.formatters')
-- local util = require 'lspconfig.util'
--
-- -- =============================================================================
-- -- Helper Functions
-- -- =============================================================================
--
-- --- Get LSP client capabilities with completion and blink support
-- local function get_capabilities()
-- 	local __get = function()
-- 		local _, cmp = pcall(require, 'cmp_nvim_lsp')
-- 		local _, blink = pcall(require, 'blink.cmp')
--
-- 		if blink then return blink.get_lsp_capabilities() end
-- 		if cmp then return cmp.default_capabilities() end
--
-- 		return vim.lsp.protocol.make_client_capabilities()
-- 	end
--
-- 	local cap = __get()
--
-- 	cap.textDocument.completion.completionItem.snippetSupport = true
--
-- 	return cap;
-- end
--
-- local capabilities = get_capabilities()
--
-- --- On attach function for LSP clients
-- local function on_attach(client, bufnr)
-- 	-- Future: Add workspace diagnostics if needed
-- 	-- require("workspace-diagnostics").populate_workspace_diagnostics(client, bufnr)
-- end
--
-- -- =============================================================================
-- -- Language Server Configurations and Startup
-- -- =============================================================================
--
-- -- Choose TypeScript LSP: "vtsls" or "ts_ls"
-- local typescript_lsp = "vtsls" -- Change to "vtsls" for full refactoring support
--
-- -- Performance mode: Enables aggressive optimizations for large projects (and lower memory).
-- -- When true: Disables autoimports, suggestions, and expensive processing for maximum speed
-- --             BUT keeps essential features: hover, go-to-definition, references, rename
-- -- When false: Full features enabled (autoimports, completions, suggestions, etc.)
-- -- See reports/nvim-memory-investigation.md for full memory analysis.
-- local performance_mode = false
--
-- vim.lsp.config('jsonls', {
-- 	capabilities = capabilities,
-- 	cmd = { 'vscode-json-language-server', '--stdio' },
-- 	settings = {
-- 		json = {
-- 			schemas = {
-- 				{
-- 					fileMatch = { 'package.json' },
-- 					url = 'https://json.schemastore.org/package.json',
-- 				},
-- 				{
-- 					fileMatch = { 'tsconfig.json', 'tsconfig.*.json' },
-- 					url = 'https://json.schemastore.org/tsconfig.json',
-- 				},
-- 				{
-- 					fileMatch = { '.prettierrc', '.prettierrc.json', '.prettierrc.yml' },
-- 					url = 'https://json.schemastore.org/prettierrc.json',
-- 				},
-- 				{
-- 					fileMatch = { '.eslintrc', '.eslintrc.json', '.eslintrc.yml' },
-- 					url = 'https://json.schemastore.org/eslintrc.json',
-- 				},
-- 				{
-- 					fileMatch = { '.github/**/.github/workflows/*.yml' },
-- 					url = 'https://json.schemastore.org/github-workflow.json',
-- 				},
-- 			},
-- 		},
-- 	},
-- })
--
--
-- -- Register TypeScript Language Server (official);
-- vim.lsp.config.ts_ls = {
-- 	filetypes = { "javascript", "javascriptreact", "typescript", "typescriptreact" },
-- 	root_markers = { 'tsconfig.json', 'jsconfig.json', '.git', 'package.json' },
-- 	capabilities = capabilities,
-- 	on_attach = on_attach,
-- 	init_options = {
-- 		maxTsServerMemory = performance_mode and 2048 or 4096, -- Lower in performance mode
-- 		preferences = {
-- 			includeInlayParameterNameHints = "none",
-- 			includeInlayParameterNameHintsWhenArgumentMatchesName = false,
-- 			includeInlayFunctionParameterTypeHints = false,
-- 			includeInlayVariableTypeHints = false,
-- 			includeInlayPropertyDeclarationTypeHints = false,
-- 			includeInlayFunctionLikeReturnTypeHints = false,
-- 			includeInlayEnumMemberValueHints = false,
-- 		},
-- 	},
-- 	settings = {
-- 		typescript = {
-- 			preferences = {
-- 				includePackageJsonAutoImports = performance_mode and "off" or "auto",
-- 				updateImportsOnFileMove = performance_mode and "never" or "prompt",
-- 			},
-- 			suggest = {
-- 				autoImports = not performance_mode, -- Only disable autoimports in perf mode
-- 				enabled = true,             -- Always keep suggestions enabled
-- 			},
-- 		},
-- 		javascript = {
-- 			preferences = {
-- 				includePackageJsonAutoImports = performance_mode and "off" or "auto",
-- 				updateImportsOnFileMove = performance_mode and "never" or "prompt",
-- 			},
-- 			suggest = {
-- 				autoImports = not performance_mode, -- Only disable autoimports in perf mode
-- 				enabled = true,             -- Always keep suggestions enabled
-- 			},
-- 		},
-- 	},
-- }
--
-- -- -- Clean up any conflicting LSP clients from old configurations
-- -- vim.api.nvim_create_autocmd("VimEnter", {
-- -- 	callback = function()
-- -- 		-- Only stop clients that might conflict (duplicates from old lspconfig setup)
-- -- 		-- We allow VTSLS and Biome to coexist as they serve different purposes
-- -- 		local clients = vim.lsp.get_clients()
-- -- 		local seen = {}
-- --
-- -- 		for _, client in ipairs(clients) do
-- -- 			local key = client.name .. ":" .. (client.root_dir or "")
-- -- 			if seen[key] then
-- -- 				-- This is a duplicate, stop it
-- -- 				vim.lsp.stop_client(client.id)
-- -- 			else
-- -- 				seen[key] = true
-- -- 			end
-- -- 		end
-- -- 	end,
-- -- })
--
-- -- VTSLS (TypeScript/JavaScript) - Full Refactoring Support
-- vim.lsp.config.vtsls = {
-- 	-- Command and arguments - OPTIMIZED for monorepo performance
-- 	cmd = performance_mode and {
-- 		"vtsls",
-- 		"--stdio",
-- 		"--node-options=--max-old-space-size=4096,--max-semi-space-size=64,--optimize-for-size,--gc-interval=50"
-- 	} or {
-- 		"vtsls",
-- 		"--stdio",
-- 		"--node-options=--max-old-space-size=8192,--max-semi-space-size=128,--optimize-for-size,--gc-interval=100"
-- 	},
--
-- 	-- File types this LSP handles
-- 	filetypes = { "javascript", "javascriptreact", "typescript", "typescriptreact" },
--
-- 	-- Root directory markers
-- 	root_markers = { 'tsconfig.json', 'jsconfig.json', '.git', 'package.json' },
--
-- 	-- Capabilities and attach function
-- 	capabilities = capabilities,
-- 	on_attach = on_attach,
--
-- 	-- Performance optimizations - INCREASED debounce for monorepo
-- 	flags = {
-- 		debounce_text_changes = performance_mode and 500 or 300, -- Higher in performance mode
-- 		exit_timeout = 1000,
-- 	},
--
-- 	-- TypeScript server configuration
-- 	init_options = {
-- 		maxTsServerMemory = performance_mode and 2048 or 4096, -- Lower in performance mode
-- 		-- Performance optimizations for large monorepos
-- 		allowRenameOfImportPath = false,
-- 		allowTextChangesInNewFiles = false,
-- 		preferences = {
-- 			-- Performance preferences
-- 			includeInlayParameterNameHints = "none",
-- 			includeInlayParameterNameHintsWhenArgumentMatchesName = false,
-- 			includeInlayFunctionParameterTypeHints = false,
-- 			includeInlayVariableTypeHints = false,
-- 			includeInlayPropertyDeclarationTypeHints = false,
-- 			includeInlayFunctionLikeReturnTypeHints = false,
-- 			includeInlayEnumMemberValueHints = false,
-- 			allowRenameOfImportPath = false,
-- 			allowTextChangesInNewFiles = false,
-- 		},
-- 		-- File watching optimization - STRICT exclusions for performance
-- 		watchOptions = {
-- 			excludeDirectories = {
-- 				-- Dependencies
-- 				"**/node_modules/**",
-- 				"**/jspm_packages/**",
-- 				"**/bower_components/**",
-- 				"**/vendor/**",
--
-- 				-- Build outputs
-- 				"**/dist/**",
-- 				"**/build/**",
-- 				"**/out/**",
-- 				"**/.next/**",
-- 				"**/.nuxt/**",
-- 				"**/.vuepress/**",
-- 				"**/.cache/**",
-- 				"**/.parcel-cache/**",
-- 				"**/.nyc_output/**",
--
-- 				-- Test coverage
-- 				"**/coverage/**",
-- 				"**/.coverage/**",
-- 				"**/lcov-report/**",
--
-- 				-- Version control
-- 				"**/.git/**",
-- 				"**/.svn/**",
-- 				"**/.hg/**",
--
-- 				-- Logs and temp
-- 				"**/logs/**",
-- 				"**/*.log",
-- 				"**/tmp/**",
-- 				"**/temp/**",
-- 				"**/.tmp/**",
--
-- 				-- IDE/Editor
-- 				"**/.vscode/**",
-- 				"**/.idea/**",
-- 				"**/.vs/**",
-- 				"**/.settings/**",
--
-- 				-- OS specific
-- 				"**/.DS_Store/**",
-- 				"**/Thumbs.db/**",
-- 				"**/__pycache__/**",
-- 				"**/.pytest_cache/**",
--
-- 				-- Package manager
-- 				"**/.yarn/cache/**",
-- 				"**/.yarn/install-state.gz",
-- 				"**/.npm/**",
-- 				"**/.pnpm/**",
-- 			},
-- 			excludeFiles = {
-- 				-- Logs
-- 				"**/*.log",
-- 				"**/*.pid",
-- 				"**/*.seed",
-- 				"**/*.pid.lock",
--
-- 				-- Coverage
-- 				"**/coverage/**",
-- 				"**/lcov.info",
--
-- 				-- Build artifacts
-- 				"**/dist/**",
-- 				"**/build/**",
--
-- 				-- Cache files
-- 				"**/.cache/**",
-- 				"**/tsconfig.tsbuildinfo",
--
-- 				-- Lock files (don't watch these)
-- 				"**/package-lock.json",
-- 				"**/yarn.lock",
-- 				"**/pnpm-lock.yaml",
-- 				"**/bun.lockb",
-- 			},
-- 		},
-- 	},
--
-- 	-- Settings for TypeScript and JavaScript
-- 	settings = {
-- 		typescript = {
-- 			preferences = {
-- 				-- Performance optimizations
-- 				includePackageJsonAutoImports = performance_mode and "off" or "auto",
-- 				updateImportsOnFileMove = performance_mode and "never" or "prompt",
-- 				disableSuggestions = false,           -- Keep suggestions enabled
-- 				quotePreference = "single",
-- 				includeCompletionsForImportStatements = true, -- Keep completions enabled
-- 				includeCompletionsForModuleExports = false,
-- 				includeAutomaticOptionalChainCompletions = false,
-- 				displayPartsForJSDoc = false,
-- 				importModuleSpecifierPreference = "project-relative",
-- 				importModuleSpecifierEnding = "minimal",
-- 				generateReturnInDocTemplate = false,
-- 				allowRenameOfImportPath = false,
-- 				providePrefixAndSuffixTextForRename = false,
-- 				allowTextChangesInNewFiles = false,
-- 				lazyConfiguredProjectsFromExternalProject = true,
-- 				-- Enable refactoring
-- 				disableLanguageServiceBasedQuickFixes = true,
-- 				disableLanguageServiceBasedCodeActions = true,
-- 				disableSourceDefinitionSearch = true,
-- 				disableGoToSourceDefinition = true,
-- 			},
-- 			suggest = {
-- 				completeFunctionCalls = false,
-- 				autoImports = not performance_mode, -- Only disable autoimports in perf mode
-- 				enabled = true,             -- Keep suggestions enabled
-- 			},
-- 			workspaceSymbol = {
-- 				search = {
-- 					kind = "onlyExportedSymbols",
-- 				},
-- 			},
-- 			format = {
-- 				enable = false,
-- 			},
-- 			referencesCodeLens = {
-- 				enabled = false,
-- 			},
-- 			implementationsCodeLens = {
-- 				enabled = false,
-- 			},
-- 			semanticTokens = {
-- 				multilineTokenSupport = false,
-- 				overlappingTokenSupport = false,
-- 			},
-- 		},
-- 		javascript = {
-- 			preferences = {
-- 				-- Mirror all TypeScript optimizations
-- 				includeInlayParameterNameHints = "none",
-- 				includeInlayParameterNameHintsWhenArgumentMatchesName = false,
-- 				includeInlayFunctionParameterTypeHints = false,
-- 				includeInlayVariableTypeHints = false,
-- 				includeInlayPropertyDeclarationTypeHints = false,
-- 				includeInlayFunctionLikeReturnTypeHints = false,
-- 				includeInlayEnumMemberValueHints = false,
-- 				includePackageJsonAutoImports = performance_mode and "off" or "auto",
-- 				updateImportsOnFileMove = performance_mode and "never" or "prompt",
-- 				disableSuggestions = false, -- Keep suggestions enabled
-- 				quotePreference = "single",
-- 				includeCompletionsForImportStatements = true,
-- 				includeCompletionsForModuleExports = false,
-- 				includeAutomaticOptionalChainCompletions = false,
-- 				displayPartsForJSDoc = false,
-- 				importModuleSpecifierPreference = "project-relative",
-- 				importModuleSpecifierEnding = "minimal",
-- 				generateReturnInDocTemplate = false,
-- 				allowRenameOfImportPath = false,
-- 				providePrefixAndSuffixTextForRename = false,
-- 				allowTextChangesInNewFiles = false,
-- 				lazyConfiguredProjectsFromExternalProject = true,
-- 				disableLanguageServiceBasedQuickFixes = true,
-- 				disableLanguageServiceBasedCodeActions = true,
-- 				disableSourceDefinitionSearch = true,
-- 				disableGoToSourceDefinition = true,
-- 			},
-- 			suggest = {
-- 				completeFunctionCalls = false,
-- 				autoImports = not performance_mode, -- Only disable autoimports in perf mode
-- 				enabled = true,             -- Keep suggestions enabled
-- 			},
-- 			format = {
-- 				enable = false,
-- 			},
-- 			referencesCodeLens = {
-- 				enabled = false,
-- 			},
-- 			implementationsCodeLens = {
-- 				enabled = false,
-- 			},
-- 		},
-- 		vtsls = {
-- 			-- Enable full refactoring support
-- 			enableMoveToFileCodeAction = true,
-- 			enableFileReferences = true,
-- 			enableRenameFileRefactoring = true,
-- 			enableCallHierarchy = false, -- Keep disabled for performance
-- 			enableTypeHierarchy = false, -- Keep disabled for performance
--
-- 			experimental = {
-- 				completion = {
-- 					enableServerSideFuzzyMatch = true,
-- 					entriesLimit = 30,
-- 					maxSemanticsTokensNumber = 100,
-- 				},
-- 				enableProjectDiagnostics = false,
-- 				enableWorkspaceDiagnostics = false,
-- 				-- Enable refactoring actions - DISABLED for monorepo performance
-- 				enableSourceActions = false, -- Disabled for performance
-- 				enableRefactorActions = false, -- Disabled for performance
-- 			},
--
-- 			-- TypeScript server optimization - AGGRESSIVE performance settings
-- 			tsserver = {
-- 				maxTsServerMemory = performance_mode and 2048 or 4096, -- Lower in performance mode
-- 				globalPlugins = {},
-- 				plugins = {},
--
-- 				-- Performance optimizations
-- 				useSyntaxServer = "never",                    -- Disabled for monorepo performance
-- 				separateSyntaxServer = false,                 -- Disabled for monorepo performance
-- 				maxFileSize = performance_mode and 524288 or 1048576, -- 512KB in perf mode, 1MB otherwise
--
-- 				-- Disable expensive features
-- 				disableAutomaticTypingAcquisition = true, -- Don't auto-download types
-- 				enable = {
-- 					-- Keep essential features, disable only expensive ones
-- 					semanticHighlighting = false,
-- 					completion = true, -- Always keep completion
-- 					hover = true,  -- Always keep hover (essential!)
-- 					signatureHelp = true, -- Always keep signature help
-- 					definition = true, -- Always keep go-to-definition (essential!)
-- 					references = true, -- Always keep references (essential!)
-- 					documentHighlight = false,
-- 					documentSymbol = true, -- Always keep for navigation
-- 					workspaceSymbol = false, -- Expensive in large projects
-- 					codeAction = true, -- Always keep code actions
-- 					codeLens = false,
-- 					documentFormatting = false,
-- 					documentRangeFormatting = false,
-- 					documentOnTypeFormatting = false,
-- 					rename = true, -- Always keep rename (essential!)
-- 					foldingRange = false,
-- 					selectionRange = false,
-- 					linkedEditingRange = false,
-- 					callHierarchy = false,
-- 					typeHierarchy = false,
-- 					semanticTokens = false,
-- 					inlayHints = false,
-- 				},
--
-- 				-- Logging optimizations
-- 				logFile = nil, -- Disable file logging
-- 				logVerbosity = "off", -- Minimal logging
--
-- 				-- Cache optimizations
-- 				typingsCacheLocation = vim.fn.stdpath("cache") .. "/typescript", -- Custom cache location
--
-- 				watchOptions = {
-- 					watchFile = "useFsEvents",
-- 					watchDirectory = "useFsEvents",
-- 					fallbackPolling = "dynamicPriority",
-- 					synchronousWatchDirectory = true,
-- 					excludeDirectories = {
-- 						-- Dependencies (same as above)
-- 						"**/node_modules/**",
-- 						"**/jspm_packages/**",
-- 						"**/bower_components/**",
-- 						"**/vendor/**",
--
-- 						-- Build outputs
-- 						"**/dist/**",
-- 						"**/build/**",
-- 						"**/out/**",
-- 						"**/.next/**",
-- 						"**/.nuxt/**",
-- 						"**/.vuepress/**",
-- 						"**/.cache/**",
-- 						"**/.parcel-cache/**",
-- 						"**/.nyc_output/**",
--
-- 						-- Test coverage
-- 						"**/coverage/**",
-- 						"**/.coverage/**",
-- 						"**/lcov-report/**",
--
-- 						-- Version control
-- 						"**/.git/**",
-- 						"**/.svn/**",
-- 						"**/.hg/**",
--
-- 						-- Logs and temp
-- 						"**/logs/**",
-- 						"**/tmp/**",
-- 						"**/temp/**",
-- 						"**/.tmp/**",
--
-- 						-- IDE/Editor
-- 						"**/.vscode/**",
-- 						"**/.idea/**",
-- 						"**/.vs/**",
-- 						"**/.settings/**",
--
-- 						-- OS specific
-- 						"**/.DS_Store/**",
-- 						"**/Thumbs.db/**",
-- 						"**/__pycache__/**",
-- 						"**/.pytest_cache/**",
--
-- 						-- Package manager
-- 						"**/.yarn/cache/**",
-- 						"**/.yarn/install-state.gz",
-- 						"**/.npm/**",
-- 						"**/.pnpm/**",
-- 					},
-- 				},
-- 			},
-- 		},
-- 	},
-- }
--
-- -- Biome LSP - Fast Linting and Formatting
-- -- Runs alongside VTSLS for complementary functionality (linting vs language features)
-- vim.lsp.config('biome', {
-- 	cmd = function(dispatchers, config)
-- 		local cmd = 'biome'
-- 		if (config or {}).root_dir then
-- 			local local_cmd = vim.fs.joinpath(config.root_dir, 'node_modules/.bin', cmd)
-- 			if vim.fn.executable(local_cmd) == 1 then
-- 				cmd = local_cmd
-- 			end
-- 		end
-- 		return vim.lsp.rpc.start({ cmd, 'lsp-proxy' }, dispatchers)
-- 	end,
-- 	filetypes = {
-- 		'astro',
-- 		'css',
-- 		'graphql',
-- 		'html',
-- 		'javascript',
-- 		'javascriptreact',
-- 		'json',
-- 		'jsonc',
-- 		'svelte',
-- 		'typescript',
-- 		'typescriptreact',
-- 		'vue',
-- 	},
-- 	workspace_required = true,
-- 	root_dir = function(bufnr, on_dir)
-- 		-- The project root is where the LSP can be started from
-- 		-- As stated in the documentation above, this LSP supports monorepos and simple projects.
-- 		-- We select then from the project root, which is identified by the presence of a package
-- 		-- manager lock file.
-- 		local root_markers = {
-- 			'package-lock.json',
-- 			'yarn.lock',
-- 			'pnpm-lock.yaml',
-- 			'bun.lockb',
-- 			'bun.lock',
-- 			'deno.lock',
-- 		}
-- 		-- Set a lower priority to avoid spawning multiple servers on monorepos
-- 		local biome_config_files = { 'biome.json', 'biome.jsonc' }
-- 		-- Give the root markers equal priority by wrapping them in a table
-- 		root_markers = vim.fn.has('nvim-0.11.3') == 1 and { root_markers, biome_config_files, { '.git' } }
-- 		or vim.list_extend(root_markers, vim.list_extend(biome_config_files, { '.git' }))
--
-- 		-- We fallback to the current working directory if no project root is found
-- 		local project_root = vim.fs.root(bufnr, root_markers) or vim.fn.getcwd()
--
-- 		-- We know that the buffer is using Biome if it has a config file
-- 		-- in its directory tree.
-- 		local filename = vim.api.nvim_buf_get_name(bufnr)
-- 		biome_config_files = util.insert_package_json(biome_config_files, 'biomejs', filename)
-- 		local is_buffer_using_biome = vim.fs.find(biome_config_files, {
-- 			path = filename,
-- 			type = 'file',
-- 			limit = 1,
-- 			upward = true,
-- 			stop = vim.fs.dirname(project_root),
-- 		})[1]
-- 		if not is_buffer_using_biome then
-- 			return
-- 		end
--
-- 		on_dir(project_root)
-- 	end,
-- 	capabilities = capabilities,
-- 	on_attach = on_attach,
-- })
--
-- -- just-lsp: Language server for justfiles
-- vim.lsp.config('just', {
-- 	cmd = { 'just-lsp' },
-- 	filetypes = { 'just' },
-- 	root_markers = { 'justfile', 'Justfile', '.justfile' },
-- 	capabilities = capabilities,
-- })
--
-- -- oxlint: Fast linting for JS/TS (complements biome/vtsls)
-- vim.lsp.config('oxlint', {
-- 	cmd = { 'oxlint', '--lsp' },
-- 	filetypes = { 'javascript', 'typescript', 'javascriptreact', 'typescriptreact' },
-- 	root_markers = { 'oxlint.json', 'oxlintrc.json', '.oxlint.json', '.oxlintrc.json', },
-- 	capabilities = capabilities,
-- 	settings = {},
-- })
--
-- vim.lsp.config('jsonls', {
-- 	cmd = function(dispatchers, config)
-- 		local cmd = 'vscode-json-language-server'
-- 		if (config or {}).root_dir then
-- 			local local_cmd = vim.fs.joinpath(config.root_dir, 'node_modules/.bin', cmd)
-- 			if vim.fn.executable(local_cmd) == 1 then
-- 				cmd = local_cmd
-- 			end
-- 		end
-- 		return vim.lsp.rpc.start({ cmd, '--stdio' }, dispatchers)
-- 	end,
-- 	filetypes = { 'json', 'jsonc' },
-- 	init_options = {
-- 		provideFormatter = true,
-- 	},
-- 	root_markers = { '.git' },
-- })
--
-- vim.lsp.config('lua_ls', {
-- 	on_init = function(client)
-- 		if client.workspace_folders then
-- 			local path = client.workspace_folders[1].name
-- 			if
-- 				 path ~= vim.fn.stdpath('config')
-- 				 and (vim.uv.fs_stat(path .. '/.luarc.json') or vim.uv.fs_stat(path .. '/.luarc.jsonc'))
-- 			then
-- 				return
-- 			end
-- 		end
--
-- 		client.config.settings.Lua = vim.tbl_deep_extend('force', client.config.settings.Lua, {
-- 			runtime = {
-- 				-- Tell the language server which version of Lua you're using (most
-- 				-- likely LuaJIT in the case of Neovim)
-- 				version = 'LuaJIT',
-- 				-- Tell the language server how to find Lua modules same way as Neovim
-- 				-- (see `:h lua-module-load`)
-- 				path = {
-- 					'lua/?.lua',
-- 					'lua/?/init.lua',
-- 				},
-- 			},
-- 			-- Make the server aware of Neovim runtime files
-- 			workspace = {
-- 				checkThirdParty = false,
-- 				library = {
-- 					vim.env.VIMRUNTIME
-- 					-- Depending on the usage, you might want to add additional paths
-- 					-- here.
-- 					-- '${3rd}/luv/library'
-- 					-- '${3rd}/busted/library'
-- 				}
-- 				-- Or pull in all of 'runtimepath'.
-- 				-- NOTE: this is a lot slower and will cause issues when working on
-- 				-- your own configuration.
-- 				-- See https://github.com/neovim/nvim-lspconfig/issues/3189
-- 				-- library = {
-- 				--   vim.api.nvim_get_runtime_file('', true),
-- 				-- }
-- 			}
-- 		})
-- 	end,
-- 	settings = {
-- 		Lua = {}
-- 	}
-- })
--
-- -- Enable LSP servers
--
-- -- =============================================================================
-- -- LSP Handlers and Optimizations
-- -- =============================================================================
--
-- -- Diagnostic hover on cursor hold
-- vim.api.nvim_create_augroup("lsp_diagnostics_hold", { clear = true })
-- vim.api.nvim_create_autocmd({ "CursorHold" }, {
-- 	pattern = "*",
-- 	callback = function()
-- 		-- Do not open diagnostic float if any float is already open (e.g. hover)
-- 		local float_open = false
-- 		for _, win in ipairs(vim.api.nvim_list_wins()) do
-- 			local config = vim.api.nvim_win_get_config(win)
-- 			if config.relative ~= "" then
-- 				float_open = true
-- 				break
-- 			end
-- 		end
--
-- 		if not float_open then
-- 			vim.diagnostic.open_float(nil, {
-- 				scope = "cursor",
-- 				focusable = false,
-- 				close_events = {
-- 					"CursorMoved",
-- 					"CursorMovedI",
-- 					"BufHidden",
-- 					"InsertCharPre",
-- 					"WinLeave",
-- 				},
-- 			})
-- 		end
-- 	end,
-- 	group = "lsp_diagnostics_hold",
-- })
--
-- -- Update time for diagnostics
-- vim.opt.updatetime = 300
--
-- local function with_handler_config(handler, config)
-- 	return function(err, result, ctx, handler_config)
-- 		return handler(err, result, ctx, vim.tbl_deep_extend("force", handler_config or {}, config))
-- 	end
-- end
--
-- -- LSP hover and signature help styling
-- vim.lsp.handlers['textDocument/hover'] = with_handler_config(
-- 	vim.lsp.handlers.hover,
-- 	{ border = 'none' }
-- )
--
-- vim.lsp.handlers['textDocument/signatureHelp'] = with_handler_config(
-- 	vim.lsp.handlers.signature_help,
-- 	{ border = 'none' }
-- )
--
-- -- Diagnostic configuration
-- vim.diagnostic.config({
-- 	virtual_text = false,
-- 	update_in_insert = false,
-- 	severity_sort = true,
-- 	float = {
-- 		border = 'none',
-- 		source = false,
-- 	},
-- 	signs = {
-- 		severity_limit = "Error",
-- 	},
-- })
--
-- -- Code action timeout optimized for refactoring
-- vim.lsp.handlers['textDocument/codeAction'] = with_handler_config(
-- 	vim.lsp.handlers['textDocument/codeAction'], {
-- 		timeout_ms = 3000, -- 3 seconds for refactoring operations
-- 	}
-- )
--
-- -- Minimal logging
-- vim.lsp.log.set_level("ERROR")
--
-- -- Neovim performance optimizations
-- vim.opt.maxmempattern = 5000
-- vim.opt.maxfuncdepth = 200
-- vim.opt.regexpengine = 1
-- vim.opt.synmaxcol = 500
--
-- -- Disable syntax highlighting for very large files
-- vim.api.nvim_create_autocmd("BufReadPre", {
-- 	pattern = "*",
-- 	callback = function()
-- 		local file_size = vim.fn.getfsize(vim.fn.expand("<afile>"))
-- 		if file_size > 1024 * 1024 then -- 1MB
-- 			vim.cmd("syntax off")
-- 			vim.opt_local.wrap = false
-- 			vim.opt_local.number = false
-- 			vim.opt_local.relativenumber = false
-- 		end
-- 	end,
-- })
--
-- -- =============================================================================
-- -- Format-on-Save Configuration
-- -- =============================================================================
--
-- local function stop_path()
-- 	local path = vim.fn.system("git rev-parse --show-toplevel")
--
-- 	if path:sub(1, 1) == "/" then
-- 		return path
-- 	end
--
-- 	return vim.fn.expand("%:p:h")
-- end
--
-- -- Format-on-save for JS/TS files (Biome formatting via shell, not LSP)
-- local js = {
-- 	formatters.remove_trailing_whitespace,
-- 	formatters.remove_trailing_newlines,
-- 	formatters.if_file_exists({
-- 		pattern = { "eslint.config.*" },
-- 		stop_path = stop_path,
-- 		formatter = formatters.shell({
-- 			cmd = { "eslint", "--stdin-filename", "%", " --fix-to-stdout" },
-- 		})
-- 	}),
-- 	formatters.if_file_exists({
-- 		pattern = { ".prettierrc", ".prettierrc.*", "prettier.config.*" },
-- 		stop_path = stop_path,
-- 		formatter = formatters.shell({
-- 			cmd = { "prettier", "--stdin-filepath", "%" },
-- 		})
-- 	}),
-- 	oxfmt_fmt,
-- 	formatters.if_file_exists({
-- 	  pattern = { "biome.json", "biome.jsonc" },
-- 	  stop_path = stop_path,
-- 	  formatter = formatters.shell({
-- 	    cmd = { "biome", "format", "--fix", "--stdin-file-path", "%" },
-- 	  })
-- 	}),
-- }
--
-- -- oxfmt formatter for JS/TS/JSON (used as fallback when no prettier/biome config)
-- local oxfmt_fmt = formatters.shell({
-- 	pattern = { ".oxfmt.json" },
-- 	stop_path = stop_path,
-- 	cmd = { 'oxfmt', '--stdin-filepath', '%' },
-- })
--
-- format_on_save.setup({
-- 	stderr_loglevel = vim.log.levels.OFF,
-- 	auto_commands = true,
-- 	exclude_path_patterns = {
-- 		"/node_modules/",
-- 		".local/share/nvim/lazy",
-- 	},
-- 	experiments = {
-- 		partial_update = 'diff',
-- 	},
-- 	formatter_by_ft = {
-- 		css = js,
-- 		html = formatters.lsp,
-- 		clojure = formatters.lsp,
-- 		java = formatters.lsp,
-- 		lua = formatters.lsp,
-- 		pug = formatters.lsp,
-- 		openscad = formatters.lsp,
-- 		python = formatters.lsp,
-- 		rust = formatters.lsp,
-- 		scad = formatters.lsp,
-- 		scss = formatters.lsp,
-- 		sh = formatters.shfmt,
-- 		terraform = formatters.lsp,
-- 		yaml = formatters.lsp,
-- 		gleam = formatters.lsp,
-- 		just = formatters.lsp,
-- 		json = formatters.lsp,
--
-- 		-- my_custom_formatter = function()
-- 		-- 	if vim.api.nvim_buf_get_name(0):match("/README.md$") then
-- 		-- 		return formatters.prettierd
-- 		-- 	else
-- 		-- 		return formatters.lsp()
-- 		-- 	end
-- 		-- end,
--
-- 		javascript = vim.list_extend({}, js), -- copy js chain, don't mutate original
-- 		typescript = js,
-- 		svelte = js,
-- 		typescriptreact = js,
-- 		javascriptreact = js,
-- 	},
-- })
--
vim.lsp.enable('biome');
vim.lsp.enable('vtsls');
vim.lsp.enable('lua_ls');
vim.lsp.enable('jsonls');
vim.lsp.enable('just');
vim.lsp.enable('oxlint');
vim.lsp.enable('oxfmt');
