#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# find the linkers and run them iteratively
find . -name link.sh | while read installer ; do sh -c "${installer}" ; done
