vim.g.multi_cursor_use_default_mapping = 0
vim.g.multi_cursor_start_word_key      = '<C-]>'
-- vim.g.multi_cursor_select_all_word_key = '<C-S-]>'
-- vim.g.multi_cursor_start_key           = 'g<A-n>'
-- vim.g.multi_cursor_select_all_key      = 'g<A-N>'
vim.g.multi_cursor_next_key            = '<C-]>'
vim.g.multi_cursor_prev_key            = '<C-[>'
vim.g.multi_cursor_skip_key            = '<C-x>'
vim.g.multi_cursor_quit_key            = '<Esc>'
